export const FETCH_DATA = 'FETCH_DATA'
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS'
export const FETCH_DATA_FAIL = 'FETCH_DATA_FAIL'

export const FETCH_HOURLY_SUCCESS = 'FETCH_HOURLY_SUCCESS'
export const FETCH_HOURLY_FAIL = 'FETCH_HOURLY_FAIL'

export const SET_COORDS = 'SET_COORDS'
